name: "Bug report"
description: File a bug report
labels: [bug, pending triage]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to file this bug report.
  - type: textarea
    attributes:
      label: Bug description
      description: A clear and concise description of what the bug is.
      placeholder: Bug description
    validations:
      required: true
  - type: textarea
    attributes:
      label: Reproduction
      description: |
        Test new line \n a
      placeholder: Reproduction
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Node.js package manager
      description: Select the used Node.js package manager
      options:
        - npm
        - yarn
        - pnpm
    validations:
      required: true
  - type: textarea
    attributes:
      label: Environment
      description: |
        Run and paste the output of:\n`npx envinfo --system --npmPackages webpack,esbuild-loader --binaries --browsers`
      render: shell
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Can you contribute a fix?
      description: Let us know if you plan to open a pull request to fix this bug!
      options:
        - label: I plan to submit a pull request for this issue.
